/* =====================================================================
 * Schulformulare - app logic & shared render helpers
 *
 * Form templates live in templates/*.js and register themselves via
 * registerTemplate(). Each template provides:
 *   id, label     - identifier and dropdown label
 *   fields        - input definitions for the form panel; either an array
 *                   or a function of the current data (dynamic field lists)
 *   view(d)       - maps raw input state to the template's view model
 *                   (formatting, computed values); Mustache stays logic-less
 * Optional members: description (shown under the dropdown), dataFiles
 * (JSON fetched into t.data), panelInfo(d) (live info line below the
 * fields). The sheet markup itself is NOT part of the object: app.js loads
 * templates/<id>.mustache into t.template, plus an optional accompanying
 * <id>.notes.html. The template files are discovered via
 * templates/manifest.json and loaded dynamically; the dropdown is sorted
 * by label.
 * ===================================================================== */

const WEEKDAYS = ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag"];

// Accepts ISO dates only (what date inputs and the data files produce) -
// anything else renders empty instead of leaking raw input into the sheet
const fmtDate = iso => {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(iso || "")) return "";
  const [y, m, d] = iso.split("-");
  return `${d}.${m}.${y}`;
};

// Difference between two HH:MM strings in hours; 0 while incomplete
function diffHours(from, to) {
  if (!from || !to) return 0;
  const [fh, fm] = from.split(":").map(Number);
  const [th, tm] = to.split(":").map(Number);
  return Math.max(0, (th * 60 + tm - (fh * 60 + fm)) / 60);
}

// "7:45" (H:MM) from a decimal hour value
const fmtHours = h => {
  const m = Math.round(h * 60);
  return `${Math.floor(m / 60)}:${String(m % 60).padStart(2, "0")}`;
};

// "2026/27" - German school years start on August 1st
function currentSchoolYear() {
  const now = new Date();
  const y = now.getMonth() >= 7 ? now.getFullYear() : now.getFullYear() - 1;
  return `${y}/${String(y + 1).slice(2)}`;
}

// Escaped value, or a fill-in line when empty. Yields HTML, so templates
// must reference these values with triple mustaches: {{{value}}}
const line = v => v ? Mustache.escape(String(v)) : '<span class="fillline">&nbsp;</span>';

/* ---------- Mustache partials shared by all templates ----------
 * Markup lives in templates/partials/*.mustache ({{> sig-block}} etc.).
 * The set is discovered at startup via templates/partials/manifest.json -
 * generated by the build, served on the fly by the dev server. */
const PARTIALS = {};

// View-model parts every template needs (document header + signature row)
function baseView(d) {
  return {
    ...d,
    sigPlaceDate: line(d.place) + (d.place || d.date ? ", " : "") + fmtDate(d.date),
    sigLabel: "Unterschrift Erziehungsberechtigte/r",
    child: line(d.child),               // "Mia Muster" for running text
    childFormal: line(d.childFormal),   // "Muster, Mia" for "Name, Vorname" fields
    grade: line(d.grade),
  };
}

/* Person and school data are master data only - forms cannot override
   them and always print the values from the Stammdaten panel. Templates
   contain only genuine form fields plus selections (guardianPick etc.). */

/* ---------- Template registry ----------
 * Field types: text, date, select (options), checkbox, textarea,
 *              daygrid (Mon-Fri from/to each), timespan (one labelled
 *              from/to row), itemrow (title + count), guardianPick
 *              (signer/contact selection from master data),
 *              heading (label only) */
const TEMPLATES = [];
function registerTemplate(tpl) { TEMPLATES.push(tpl); }

/* ================= App logic ================= */
/* Form inputs are persisted locally in the browser (localStorage), kept
   per child: { tpl, child, byChild: { <childId or "">: fields } }. The
   try/catch guards against blocked storage (e.g. private mode). */
const STORAGE_KEY = "school-forms.v1";

document.addEventListener("DOMContentLoaded", async () => {
  const tplSelect = document.getElementById("tplSelect");
  const fieldsHost = document.getElementById("fieldsHost");
  const sheet = document.getElementById("sheet");
  const childRow = document.getElementById("childRow");
  const childSelect = document.getElementById("childSelect");
  const panelInfo = document.getElementById("panelInfo");
  const tplDescription = document.getElementById("tplDescription");
  const tplNotesHost = document.getElementById("tplNotesHost");
  const layout = document.querySelector(".layout");

  // Discover the form templates via manifest and load everything they
  // need: <id>.js (field definitions + view), <id>.mustache (sheet markup),
  // the shared partials and declared data files. Adding a template means
  // dropping its file pair into templates/ - no registration list anywhere.
  // Requires HTTP - locally via `npm run dev`.
  try {
    const load = async (file, assign) => {
      const res = await fetch(file);
      if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
      assign(await res.text());
    };
    const fetchJson = async file => {
      const res = await fetch(file);
      if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
      return res.json();
    };
    const loadScript = file => new Promise((resolve, reject) => {
      const s = document.createElement("script");
      s.src = file;
      s.onload = resolve;
      s.onerror = () => reject(new Error(`${file}: failed to load`));
      document.head.appendChild(s);
    });

    const [tplFiles, partialFiles] = await Promise.all([
      fetchJson("templates/manifest.json"),
      fetchJson("templates/partials/manifest.json"),
    ]);
    // skip templates that are already registered (e.g. preloaded in tests)
    const known = new Set(TEMPLATES.map(t => t.id));
    await Promise.all(tplFiles
      .filter(f => f.endsWith(".js") && !known.has(f.replace(/\.js$/, "")))
      .map(f => loadScript(`templates/${f}`)));
    // dynamic scripts finish in arbitrary order - sort the dropdown by label
    TEMPLATES.sort((a, b) => a.label.localeCompare(b.label, "de"));
    await Promise.all([
      ...TEMPLATES.map(t => load(`templates/${t.id}.mustache`, txt => { t.template = txt; })),
      // optional accompanying notes shown collapsible above the form
      ...TEMPLATES.filter(t => tplFiles.includes(`${t.id}.notes.html`))
        .map(t => load(`templates/${t.id}.notes.html`, txt => { t.notes = txt; })),
      ...partialFiles.filter(f => f.endsWith(".mustache"))
        .map(f => load(`templates/partials/${f}`, txt => { PARTIALS[f.replace(/\.mustache$/, "")] = txt; })),
      // data files a template declares, e.g. { holidays: "data/holidays.json" }
      ...TEMPLATES.flatMap(t => Object.entries(t.dataFiles || {}).map(([key, file]) =>
        load(file, txt => { (t.data ??= {})[key] = JSON.parse(txt); }))),
      // school directory feeding the master-data autocomplete - purely
      // optional, so a failure must not break the app start
      load("data/schools.json", txt => { Profiles.setSchoolDirectory(JSON.parse(txt).schools); })
        .catch(() => {}),
    ]);
  } catch (err) {
    sheet.innerHTML = `<p class="empty-note">Vorlagen konnten nicht geladen werden (${err.message}).<br>Lokal muss die Seite über einen Webserver laufen: <code>npm run dev</code></p>`;
    return;
  }

  function loadStore() {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      const parsed = raw ? JSON.parse(raw) : null;
      return parsed?.byChild ? parsed : { tpl: "", child: "", byChild: {} };
    } catch (e) { return { tpl: "", child: "", byChild: {} }; }
  }
  const store = loadStore();
  let state; // current child's bucket in store.byChild

  function persist() {
    store.tpl = tplSelect.value;
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(store));
    } catch (e) { /* storage unavailable - inputs stay in memory only */ }
  }

  TEMPLATES.forEach(t => {
    const o = document.createElement("option");
    o.value = t.id; o.textContent = t.label;
    tplSelect.appendChild(o);
  });
  if (store.tpl && TEMPLATES.some(t => t.id === store.tpl)) tplSelect.value = store.tpl;

  function currentTpl() {
    return TEMPLATES.find(t => t.id === tplSelect.value) || TEMPLATES[0];
  }

  /* ---------- Master data integration ---------- */
  const activeChildren = () => Profiles.data.children.filter(c => fullName(c));
  const namedGuardians = () => Profiles.data.guardians.filter(g => fullName(g));

  function fillSelect(sel, items) {
    sel.innerHTML = "";
    items.forEach(x => {
      const o = document.createElement("option");
      o.value = x.id; o.textContent = fullName(x);
      sel.appendChild(o);
    });
  }

  function refreshSelectors() {
    const kids = activeChildren();
    childRow.style.display = kids.length > 1 ? "" : "none";
    fillSelect(childSelect, kids);
    // reassign only when the child no longer EXISTS - a child whose name
    // was just cleared for retyping must stay active (the select shows
    // blank until the name is complete again)
    if (!Profiles.data.children.some(c => c.id === store.child)) store.child = kids[0]?.id || "";
    childSelect.value = store.child;
  }

  // default signer: the picked person, else a parent, else the first
  // contact; the guardianPick field shows the same person as its default
  // so panel and sheet never diverge
  function defaultGuardian() {
    return Profiles.data.guardians.find(g => g.id === state._guardianId && fullName(g))
      || namedGuardians().find(isParent)
      || namedGuardians()[0];
  }

  // Values inherited from master data; explicit form inputs override them
  function profileSeed() {
    const p = Profiles.data;
    const child = p.children.find(c => c.id === store.child);
    const guardian = defaultGuardian();
    // forms always print the active child's school (fallback: first school)
    const school = p.schools.find(s => s.id === child?.schoolId) || p.schools[0] || {};
    const seed = {};
    if (school.name) seed.school = school.name;
    if (school.number) seed.schoolNumber = school.number;
    // the school year is nationwide - always the computed current one;
    // forms targeting the NEXT year (e.g. Hortanmeldung) compute their own
    seed.schoolYear = currentSchoolYear();
    if (school.street) seed.schoolStreet = school.street;
    if (school.phone) seed.schoolPhone = school.phone;
    const schoolZipCity = [school.zip, school.city].filter(Boolean).join(" ");
    if (schoolZipCity) seed.schoolZipCity = schoolZipCity;
    if (child) {
      seed.child = fullName(child);
      seed.childFormal = formalName(child);
      if (child.grade) seed.grade = child.grade;
      // stored as ISO (date input); printed in German format
      if (child.birth) seed.birth = /^\d{4}-\d{2}-\d{2}$/.test(child.birth) ? fmtDate(child.birth) : child.birth;
    }
    const household = householdAddress();
    if (guardian) seed.guardian = fullName(guardian);
    // the signature place ("Ort, Datum") is where the signer lives; an own
    // (even partial) address ends the household inheritance - never mix
    const place = guardian && hasOwnAddress(guardian) ? guardian.city : household.city;
    if (place) seed.place = place;
    // the signature date defaults to today (local time, ISO like the input)
    const now = new Date();
    seed.date = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
    // all reachable guardians' numbers in one line, e.g. for the Hort
    // registration ("0151 … (Marie Muster), 0160 … (Max Muster)")
    const allPhones = p.guardians
      .filter(g => fullName(g) && (g.mobile || g.landline))
      .map(g => `${g.mobile || g.landline} (${fullName(g)})`)
      .join(", ");
    if (allPhones) seed.allPhones = allPhones;
    const childAddress = joinAddress(child) || joinAddress(household);
    if (childAddress) seed.childAddress = childAddress;
    // NB: templates with mother/father role blocks (first-aid, Hort
    // registration) read Profiles directly; their flat-key fallbacks
    // (motherNameFormal etc.) are only fed by the test fixture
    return seed;
  }

  function mergedData() {
    const out = profileSeed();
    for (const [k, v] of Object.entries(state)) {
      if (k.startsWith("_")) continue; // internal keys (_guardianId, _manual) stay out of the views
      if (v != null && v !== "") out[k] = v; // empty input = fall back to master data
    }
    return out;
  }

  // per-daygrid auto value for the "to" column (field option autoTo),
  // e.g. the fixed end of the early-morning care; refreshed in buildFields
  let gridDefaults = {};

  function buildFields() {
    const t = currentTpl();
    const seed = profileSeed();
    // template description + accompanying notes in the template panel;
    // rebuilt only on an actual template change so the notes stay open
    // while editing master data
    tplDescription.textContent = t.description || "";
    tplDescription.style.display = t.description ? "" : "none";
    if (tplNotesHost.dataset.tpl !== t.id) {
      // rendered as-is: the notes file wraps long sections in <details>
      // itself, so it decides what is collapsed and what stays visible
      tplNotesHost.innerHTML = t.notes || "";
      tplNotesHost.style.display = t.notes ? "" : "none";
      tplNotesHost.dataset.tpl = t.id;
    }
    // fields may be a function of the current data (dynamic field lists)
    const fieldList = typeof t.fields === "function" ? t.fields(mergedData()) : t.fields;
    // info-only entries (no fields) have nothing to fill in or print -
    // hide the whole form/preview area, the notes carry the content
    layout.style.display = fieldList.length ? "" : "none";
    // fields marked rebuild:true regenerate the whole panel on change
    const rebuildKeys = new Set(fieldList.filter(f => f.rebuild).map(f => f.key));
    // keyed by the grid/series name because that is what applyGridDefault
    // looks up via data-grid (for timespan fields the series, not the key)
    gridDefaults = Object.fromEntries(fieldList.filter(f => f.autoTo).map(f => [f.series || f.key, f.autoTo]));
    // checkboxes may declare `default: true` - applied while untouched
    const checkboxDefaults = Object.fromEntries(
      fieldList.filter(f => f.type === "checkbox" && f.default).map(f => [f.key, true]));
    // selects may declare a default value shown (and printed) while unset
    const selectDefaults = Object.fromEntries(
      fieldList.filter(f => f.type === "select" && f.default != null).map(f => [f.key, f.default]));
    fieldsHost.innerHTML = "";
    fieldList.forEach(f => {
      if (f.type === "heading") {
        const h = document.createElement("label");
        h.className = "field-label";
        h.style.marginTop = "20px";
        h.textContent = f.label;
        fieldsHost.appendChild(h);
        return;
      }
      if (f.type === "daygrid") {
        const grid = document.createElement("div");
        grid.className = "day-grid";
        grid.innerHTML = `<span></span><span class="colhead">von</span><span class="colhead">bis</span><span></span>`;
        WEEKDAYS.forEach((day, i) => {
          grid.innerHTML += `
            <span class="dow">${day.slice(0, 2)}</span>
            <input type="time" data-key="${f.key}${i}from" data-grid="${f.key}" aria-label="${day} von">
            <input type="time" data-key="${f.key}${i}to" data-grid="${f.key}" aria-label="${day} bis">
            <button type="button" class="remove" data-clear="${f.key}" data-rowkey="${f.key}${i}" aria-label="${day} leeren">×</button>`;
        });
        fieldsHost.appendChild(grid);
        return;
      }
      if (f.type === "timespan") { // one labelled row with from/to time inputs
        const row = document.createElement("div");
        row.className = "day-grid dates";
        const series = f.series || f.key; // rows sharing a series cascade
        row.innerHTML = `
          <span class="dow">${f.label}</span>
          <input type="time" data-key="${f.key}from" data-grid="${series}" aria-label="${f.label} von">
          <input type="time" data-key="${f.key}to" data-grid="${series}" aria-label="${f.label} bis">
          <button type="button" class="remove" data-clear="${series}" data-rowkey="${f.key}" aria-label="${f.label} leeren">×</button>`;
        fieldsHost.appendChild(row);
        return;
      }
      if (f.type === "itemrow") { // text plus small count input in one row
        const row = document.createElement("div");
        row.className = "item-row";
        row.innerHTML = `
          <input type="text" data-key="${f.key}title" aria-label="${f.label} - Titel">
          <input type="text" data-key="${f.key}count" placeholder="1" inputmode="numeric" aria-label="${f.label} - Anzahl">`;
        fieldsHost.appendChild(row);
        return;
      }
      if (f.type === "checkbox") {
        const w = document.createElement("div");
        w.className = "check-line";
        w.innerHTML = `<input type="checkbox" id="f_${f.key}" data-key="${f.key}">
                       <label for="f_${f.key}">${f.label}</label>`;
        fieldsHost.appendChild(w);
        return;
      }
      // Selection of the signing/contact person from the master data;
      // hidden with fewer than two named contacts, resets with the form
      if (f.type === "guardianPick") {
        // optional role filter, e.g. only parents may sign excuse letters
        const gs = namedGuardians().filter(g => !f.roles || f.roles.includes(g.role));
        // a picked person that was deleted or moved to a filtered-out role
        // must not survive as invisible state - the sheet would print
        // someone the (possibly hidden) picker no longer shows
        if (state._guardianId && !gs.some(g => g.id === state._guardianId)) delete state._guardianId;
        if (gs.length < 2) return;
        const pickLab = document.createElement("label");
        pickLab.className = "field-label";
        pickLab.htmlFor = "f_guardianPick";
        pickLab.textContent = f.label || "Ansprechpartner aus Stammdaten";
        const pick = document.createElement("select");
        pick.id = "f_guardianPick";
        gs.forEach(g => {
          const o = document.createElement("option");
          o.value = g.id; o.textContent = fullName(g);
          pick.appendChild(o);
        });
        // unpicked: show the same person profileSeed falls back to
        pick.value = state._guardianId ?? defaultGuardian()?.id ?? gs[0].id;
        if (pick.selectedIndex === -1) pick.value = gs[0].id;
        pick.addEventListener("input", () => {
          state._guardianId = pick.value;
          persist();
          buildFields();
        });
        fieldsHost.append(pickLab, pick);
        return;
      }
      const lab = document.createElement("label");
      lab.className = "field-label";
      lab.htmlFor = "f_" + f.key;
      lab.textContent = f.label;
      fieldsHost.appendChild(lab);
      let el;
      if (f.type === "select") {
        el = document.createElement("select");
        f.options.forEach(opt => { // plain string, or { value, label }
          const o = document.createElement("option");
          o.value = typeof opt === "object" ? opt.value : opt;
          o.textContent = (typeof opt === "object" ? opt.label : opt) || "- bitte wählen -";
          el.appendChild(o);
        });
      } else if (f.type === "textarea") {
        el = document.createElement("textarea");
        if (f.ph) el.placeholder = f.ph;
      } else {
        el = document.createElement("input");
        el.type = f.type;
        if (f.ph) el.placeholder = f.ph;
      }
      // Master-data value shows greyed as placeholder; typing overrides it,
      // clearing the input falls back to it (date/time/select can't show one)
      if (seed[f.key] && (el.type === "text" || f.type === "textarea")) el.placeholder = seed[f.key];
      el.id = "f_" + f.key;
      el.dataset.key = f.key;
      fieldsHost.appendChild(el);
    });

    // Clear buttons of day/date rows: empty the row itself plus all
    // following rows of the series that were not edited manually
    fieldsHost.querySelectorAll("button[data-clear]").forEach(btn => {
      btn.addEventListener("click", () => {
        const series = btn.dataset.clear;
        const buttons = [...fieldsHost.querySelectorAll(`button[data-clear="${series}"]`)];
        const manual = (state._manual ??= {});
        buttons.slice(buttons.indexOf(btn)).forEach((b, offset) => {
          for (const col of ["from", "to"]) {
            const k = b.dataset.rowkey + col;
            if (offset > 0 && manual[k]) continue;
            delete state[k];
            delete manual[k];
            const input = fieldsHost.querySelector(`[data-key="${k}"]`);
            if (input) input.value = "";
          }
        });
        persist();
        renderSheet();
      });
    });

    // Restore values from state (inputs survive switching templates)
    fieldsHost.querySelectorAll("[data-key]").forEach(el => {
      const k = el.dataset.key;
      if (el.type === "checkbox") el.checked = state[k] == null ? !!checkboxDefaults[k] : !!state[k];
      else {
        el.value = state[k] ?? selectDefaults[k] ?? "";
        // a stored select value without a matching option (stale holiday
        // id, option list changed) would show an empty select while the
        // sheet prints a fallback - drop it so panel and sheet agree
        if (el.tagName === "SELECT" && state[k] != null && el.value !== state[k]) {
          delete state[k];
          el.value = selectDefaults[k] ?? "";
        }
      }
      el.addEventListener("input", () => {
        state[k] = el.type === "checkbox" ? el.checked : el.value;
        if (el.dataset.grid) {
          cascadeDayValue(el);
          applyGridDefault(el);
        }
        persist();
        if (rebuildKeys.has(k)) buildFields(); else renderSheet();
      });
    });
    renderSheet();
  }

  // A day/date-row entry pre-fills the same column of all following rows
  // of its series that were not edited manually (tracked in state._manual);
  // works for the Mon-Fri grid and the holiday date rows alike
  function cascadeDayValue(el, markManual = true) {
    const col = el.dataset.key.endsWith("from") ? "from" : "to";
    const manual = (state._manual ??= {});
    if (markManual) manual[el.dataset.key] = true;
    const columnInputs = [...fieldsHost.querySelectorAll(`input[data-grid="${el.dataset.grid}"]`)]
      .filter(i => (i.dataset.key.endsWith("from") ? "from" : "to") === col);
    columnInputs.slice(columnInputs.indexOf(el) + 1).forEach(input => {
      if (manual[input.dataset.key]) return;
      state[input.dataset.key] = el.value;
      input.value = el.value;
    });
  }

  // entering a from-time auto-fills an empty, untouched to-cell with the
  // grid's autoTo value (e.g. fixed early-care end) and cascades it onward
  function applyGridDefault(el) {
    const def = gridDefaults[el.dataset.grid];
    if (!def || !el.dataset.key.endsWith("from") || !el.value) return;
    const toKey = el.dataset.key.replace(/from$/, "to");
    if (state._manual?.[toKey] || state[toKey]) return;
    const toInput = fieldsHost.querySelector(`[data-key="${toKey}"]`);
    if (!toInput) return;
    toInput.value = def;
    state[toKey] = def;
    cascadeDayValue(toInput, false); // auto value is not a manual edit
  }

  function renderSheet() {
    const t = currentTpl();
    const d = mergedData();
    sheet.innerHTML = Mustache.render(t.template, t.view ? t.view(d) : d, PARTIALS);
    // live info line below the fields (e.g. computed weekly hours)
    const info = t.panelInfo ? t.panelInfo(d) : "";
    panelInfo.textContent = info;
    panelInfo.style.display = info ? "" : "none";
    document.title = t.label + " - " + (d.child || "Schulformular");
  }

  /* The sheet is a fixed A4 box (styles.css) so the preview wraps and fills
     pages exactly like the print output. Instead of reflowing on narrow
     screens it is zoomed down to whatever width the column offers - on a
     phone that yields a small but true-to-print A4 page (pinch to read). */
  const A4_WIDTH_PX = (210 * 96) / 25.4; // the sheet's CSS width in px
  function fitSheet() {
    // the column never grows with the sheet (minmax(0, 1fr)), so measuring
    // it cannot feed back into the zoom we are about to set
    const avail = sheet.parentElement.clientWidth;
    if (!avail) return; // not laid out (yet) - keep the current zoom
    // -1px: leave the sheet's max-width fallback just out of reach, it
    // would squeeze the page narrower than A4
    const zoom = Math.min(1, (avail - 1) / A4_WIDTH_PX);
    document.documentElement.style.setProperty("--sheet-zoom", zoom.toFixed(4));
  }
  window.addEventListener("resize", fitSheet);

  /* ---------- PDF export ----------
   * Mobile Safari stamps its own header and footer (title, date, URL, page
   * number) onto every page it prints and offers no switch for it - no CSS
   * reaches that part of the print job. A PDF file printed from the Files
   * app comes out clean, so the app renders one itself: html2canvas
   * photographs the very sheet that is on screen (preview and PDF therefore
   * cannot drift apart), jsPDF places each page on A4. */
  const VENDOR_LIBS = ["vendor/html2canvas.min.js", "vendor/jspdf.umd.min.js"];
  let libsLoaded; // ~600 KB - fetched on first export, not on page load

  function loadPdfLibs() {
    libsLoaded ??= Promise.all(VENDOR_LIBS.map(src => new Promise((resolve, reject) => {
      const el = document.createElement("script");
      el.src = src;
      el.onload = resolve;
      el.onerror = () => reject(new Error(src));
      document.head.appendChild(el);
    })));
    return libsLoaded;
  }

  // An off-screen copy of the sheet at full A4 size: the preview may be
  // zoomed down (fitSheet) and shows the screen variant of the values -
  // the PDF must carry the print variant, like @media print does.
  function printableClone() {
    const holder = document.createElement("div");
    holder.style.cssText = "position:fixed;top:0;left:-10000px;width:210mm;background:#fff;";
    const clone = sheet.cloneNode(true);
    clone.style.zoom = "1";
    clone.style.boxShadow = "none";
    clone.style.background = "#fff"; // the preview's off-white paper would
                                     // show up as a tinted block on the page
    clone.querySelectorAll(".ghost, .page-break").forEach(el => el.remove());
    clone.querySelectorAll(".print-only").forEach(el => { el.style.display = "inline"; });
    holder.appendChild(clone);
    document.body.appendChild(holder);
    return { holder, clone };
  }

  async function savePdf() {
    await loadPdfLibs();
    const { jsPDF } = window.jspdf;
    const { holder, clone } = printableClone();
    try {
      // multi-page forms mark their pages; the .page boxes hold the content
      // only (the 15mm margin sits on the sheet), single-page forms are
      // captured with the sheet padding and placed edge to edge
      const pages = [...clone.querySelectorAll(".page")];
      const blocks = pages.length ? pages : [clone];
      const margin = pages.length ? 15 : 0;
      const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
      const [pw, ph] = [doc.internal.pageSize.getWidth(), doc.internal.pageSize.getHeight()];
      for (const [i, block] of blocks.entries()) {
        const canvas = await window.html2canvas(block, {
          scale: 3, // ~288 dpi on A4
          backgroundColor: "#ffffff",
          logging: false,
        });
        if (i) doc.addPage();
        // the width fits by construction; a form that outgrew its page is
        // scaled down (and centred) rather than cut off
        const ratio = canvas.height / canvas.width;
        let w = pw - 2 * margin;
        let h = w * ratio;
        if (h > ph - 2 * margin) { h = ph - 2 * margin; w = h / ratio; }
        doc.addImage(canvas.toDataURL("image/jpeg", 0.95), "JPEG",
          (pw - w) / 2, margin, w, h);
      }
      // document.title is "<template> - <child>"
      const name = document.title.replace(/[\\/:*?"<>|]/g, "") + ".pdf";
      const file = new File([doc.output("blob")], name, { type: "application/pdf" });
      // The OS share sheet is the short way on a phone: it offers "Drucken"
      // right there. Where it is unavailable - or the tap that started this
      // no longer counts as a user gesture - the file is downloaded instead.
      if (navigator.canShare?.({ files: [file] })) {
        try {
          await navigator.share({ files: [file], title: document.title });
          return;
        } catch (err) {
          if (err.name === "AbortError") return; // user closed the sheet
        }
      }
      doc.save(name);
    } finally {
      holder.remove();
    }
  }

  // "Leeren" clears only the current child's form inputs, not master data
  function resetForm() {
    store.byChild[store.child] = state = {};
    persist();
    buildFields();
  }

  function activateChild(id) {
    store.child = id;
    state = (store.byChild[store.child] ??= {});
    persist();
    buildFields();
  }

  tplSelect.addEventListener("change", () => { persist(); buildFields(); });
  childSelect.addEventListener("change", () => activateChild(childSelect.value));
  document.getElementById("printBtn").addEventListener("click", () => window.print());
  document.getElementById("resetBtn").addEventListener("click", resetForm);
  const pdfBtn = document.getElementById("pdfBtn");
  pdfBtn.addEventListener("click", async () => {
    // rendering an A4 page at 288 dpi takes a moment on a phone
    const label = pdfBtn.textContent;
    pdfBtn.disabled = true;
    pdfBtn.textContent = "PDF …";
    try {
      await savePdf();
    } catch (err) {
      window.alert("Das PDF konnte nicht erstellt werden: " + err.message);
    } finally {
      pdfBtn.disabled = false;
      pdfBtn.textContent = label;
    }
  });
  // footer: wipe EVERYTHING (master data included) and start over
  document.getElementById("wipeBtn").addEventListener("click", () => {
    if (!window.confirm("Wirklich alle gespeicherten Daten löschen?\nStammdaten und sämtliche Formulareingaben gehen verloren.")) return;
    try { localStorage.clear(); } catch (e) {}
    window.location.reload();
  });

  Profiles.renderUI(document.getElementById("profilesHost"), () => {
    // deleting a child promises "Alle zugehörigen Formulareingaben gehen
    // verloren" - drop its orphaned bucket instead of keeping it in
    // localStorage forever ("" = inputs made before the first child)
    for (const id of Object.keys(store.byChild)) {
      if (id !== "" && !Profiles.data.children.some(c => c.id === id)) delete store.byChild[id];
    }
    refreshSelectors();
    activateChild(store.child); // child may have been added/removed
  });

  refreshSelectors();
  activateChild(store.child);
  fitSheet();
});
